pm_widget_form_propel_choice_or_create:
  url:   /pm_widget_form_propel_choice_or_create
  param: { module: dc_ajax, action: getPropelChoices }

pm_widget_form_doctrine_choice_or_create:
  url:   /pm_widget_form_doctrine_choice_or_create
  param: { module: dc_ajax, action: getDoctrineChoices }

dc_widget_form_ajax_dependence_changed:
  url:   /dc_widget_form_ajax_dependence_changed
  param: { module: dc_ajax, action: dcWidgetFormAjaxDependenceChanged }

dc_widget_form_jquery_dependence_changed:
  url:  /dc_widget_form_jquery_dependence_changed
  param: { module: dc_ajax, action: dcWidgetFormJQueryDependenceChanged }

pm_widget_form_propel_jquery_search:
  url: /pm_widget_form_propel_jquery_search
  param: { module: dc_ajax, action: pmWidgetFormPropelJQuerySearch }

dc_widget_form_activator:
  url:  /dc_widget_form_activator
  param: { module: dc_ajax, action: dcWidgetFormActivator }

